name: ci-cd-bento
config:
  envs: []
  services:
    Summarization:
      instance_type: cpu.1
      scaling:
        min_replicas: 1
        max_replicas: 2
    # envs: []
    # deployment_strategy: Recreate
    # extras: {}
    # config_overrides:
    #   traffic:
    #     timeout: 30
    #     external_queue: false