name: Deploy Bento
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Build
        uses: bentoml/deploy-bento-action@main
        with:
          build: true
          action: skip
          deployment_name: summarization-cicd
          cloud_api_token: ${{ secrets.CLOUD_API_TOKEN }}
          cloud_endpoint: ${{ secrets.CLOUD_ENDPOINT }}
