name: Deploy to BentoCloud
on:
  push:
    paths:
      - 'deployment.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - uses: bentoml/setup-bentoml-action@v1
        with:
          python-version: "3.10"
          bentoml-version: ${{ inputs.bentoml_version }}
      - name: Login to Bento Cloud
        shell: bash
        run: |
          echo "Login to Cloud Console at ${{ secrets.CLOUD_ENDPOINT }}"
          bentoml cloud login --api-token ${{ secrets.CLOUD_API_TOKEN }} --endpoint ${{ secrets.CLOUD_ENDPOINT }}
      - name: Update Deployment in Bento Cloud
        shell: bash
        run: bentoml deployment update -f deployment.json
